name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull rafsunmahdi/cicd-pipeline:latest

      - name: Delete Old docker container
        run: sudo docker rm -f cicd-pipeline-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 80:8080 --name cicd-pipeline-container rafsunmahdi/cicd-pipeline:latest

      - name: Send Slack Notification (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ CD Deployment Successful!\n🎉 The deployment for *rafsunmahdi/cicd-pipeline* was successful!"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack Notification (Failure)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "❌ CD Deployment Failed!\n🚨 The deployment for *rafsunmahdi/cicd-pipeline* failed! Check GitHub Actions logs."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}