name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull rafsunmahdi/cicd-pipeline:latest

      - name: Delete Old docker container
        run: sudo docker rm -f cicd-pipeline-container || true

 
      - name: Run Docker Container
        run: sudo docker run -d -p 80:8080 --name cicd-pipeline-container rafsunmahdi/cicd-pipeline:latest

    - name: Send Slack Notification (Success)
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: "CI/CD Pipeline"
        SLACK_ICON_EMOJI: ":rocket:"
        SLACK_COLOR: "good"
        SLACK_TITLE: "✅ CI Build Passed!"
        SLACK_MESSAGE: "🎉 The CI build for *rafsunmahdi/cicd-pipeline* passed! ✅"

    - name: Send Slack Notification (Failure)
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: "CI/CD Pipeline"
        SLACK_ICON_EMOJI: ":x:"
        SLACK_COLOR: "danger"
        SLACK_TITLE: "❌ CI Build Failed!"
        SLACK_MESSAGE: "🚨 The CI build for *rafsunmahdi/cicd-pipeline* failed! Check GitHub Actions logs."