name: CI Pipeline

on:
  push:
    branches: 
      - "master"
      # This will make it run on all branches
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t rafsunmahdi/cicd-pipeline:${{ github.sha }} -t rafsunmahdi/cicd-pipeline:latest .
    
    - name: Push to Dockerhub
      run: |
        docker push rafsunmahdi/cicd-pipeline:${{ github.sha }}
        docker push rafsunmahdi/cicd-pipeline:latest

    # 📢 Send Slack Notification on Success
    - name: Send Slack Notification (Success)
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: "CI/CD Pipeline"
        SLACK_ICON_EMOJI: ":rocket:"
        SLACK_COLOR: "good"
        SLACK_TITLE: "✅ CI Build Passed!"
        SLACK_MESSAGE: "🎉 The CI build for *rafsunmahdi/cicd-pipeline* passed! ✅"

    # ❌ Send Slack Notification on Failure
    - name: Send Slack Notification (Failure)
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: "CI/CD Pipeline"
        SLACK_ICON_EMOJI: ":x:"
        SLACK_COLOR: "danger"
        SLACK_TITLE: "❌ CI Build Failed!"
        SLACK_MESSAGE: "🚨 The CI build for *rafsunmahdi/cicd-pipeline* failed! Check GitHub Actions logs."
    