name: CI Pipeline

on:
  push:
    branches: 
      - '**'  # This will match all branches
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t rafsunmahdi/cicd-pipeline:${{ github.sha }} -t rafsunmahdi/cicd-pipeline:latest .
    
    - name: Push to Dockerhub
      run: |
        docker push rafsunmahdi/cicd-pipeline:${{ github.sha }}
        docker push rafsunmahdi/cicd-pipeline:latest

    # Add Grafana metrics
    - name: Send Deployment Metrics to Grafana
      if: success()  # Only send metrics if deployment succeeded
      run: |
        curl -X POST https://amit2025.grafana.net/api/annotations \
        -H "Authorization: Bearer ${{ secrets.GRAFANA_API_KEY }}" \
        -H "Content-Type: application/json" \
        --data '{
          "tags": ["deployment"],
          "text": "New deployment completed for ${{ github.repository }} on branch ${{ github.ref_name }}",
          "time": '$(date +%s000)',
          "data": {
            "repository": "${{ github.repository }}",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "triggered_by": "${{ github.actor }}"
          }
        }'

    # 📢 Send Slack Notification on Success
    - name: Send Slack Notification (Success)
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: "CI/CD Pipeline"
        SLACK_ICON_EMOJI: ":rocket:"
        SLACK_COLOR: "good"
        SLACK_TITLE: "✅ CI Build Passed!"
        SLACK_MESSAGE: "🎉 The CI build for *rafsunmahdi/cicd-pipeline* passed! ✅"

    # ❌ Send Slack Notification on Failure
    - name: Send Slack Notification (Failure)
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: "CI/CD Pipeline"
        SLACK_ICON_EMOJI: ":x:"
        SLACK_COLOR: "danger"
        SLACK_TITLE: "❌ CI Build Failed!"
        SLACK_MESSAGE: "🚨 The CI build for *rafsunmahdi/cicd-pipeline* failed! Check GitHub Actions logs."
    
    # 📩 Send Email Notification on Success
    - name: Send Email Notification (Success)
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ CI Build Passed - rafsunmahdi/cicd-pipeline"
        html_body: |
          <h2>CI Build Success Notification</h2>
          <p>🎉 Good news! The CI build for <strong>rafsunmahdi/cicd-pipeline</strong> was successful.</p>
          <p>Build Details:</p>
          <ul>
            <li>Repository: ${{ github.repository }}</li>
            <li>Branch: ${{ github.ref_name }}</li>
            <li>Commit: ${{ github.sha }}</li>
            <li>Triggered by: ${{ github.actor }}</li>
          </ul>
        to: ${{ secrets.EMAIL_TO }}
        from: CI/CD Pipeline <${{ secrets.EMAIL_USERNAME }}>

    # 📩 Send Email Notification on Failures
    - name: Send Email Notification (Failure)
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "❌ CI Build Failed - rafsunmahdi/cicd-pipeline"
        html_body: |
          <h2>CI Build Failure Notification</h2>
          <p>🚨 The CI build for <strong>rafsunmahdi/cicd-pipeline</strong> has failed.</p>
          <p>Build Details:</p>
          <ul>
            <li>Repository: ${{ github.repository }}</li>
            <li>Branch: ${{ github.ref_name }}</li>
            <li>Commit: ${{ github.sha }}</li>
            <li>Triggered by: ${{ github.actor }}</li>
          </ul>
          <p>Please check the <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">GitHub Actions logs</a> for more details.</p>
        to: ${{ secrets.EMAIL_TO }}
        from: CI/CD Pipeline <${{ secrets.EMAIL_USERNAME }}>
